import questionModel from "./models/question_schema.js";

const questions = [
  // Week 1 - Arrays, Strings, Two Pointers
  { question_name: "Two Sum", difficulty: "Easy", topic: "Hashing" },
  { question_name: "Best Time to Buy and Sell Stock", difficulty: "Easy", topic: "Array" },
  { question_name: "Contains Duplicate", difficulty: "Easy", topic: "Hashing" },
  { question_name: "Product of Array Except Self", difficulty: "Medium", topic: "Array" },
  { question_name: "Maximum Subarray", difficulty: "Medium", topic: "Array" },
  { question_name: "Rotate Array", difficulty: "Medium", topic: "Array" },
  { question_name: "Merge Sorted Array", difficulty: "Easy", topic: "Two Pointers" },
  { question_name: "Set Matrix Zeroes", difficulty: "Medium", topic: "Matrix" },
  { question_name: "Valid Palindrome", difficulty: "Easy", topic: "Two Pointers" },
  { question_name: "Two Sum II - Input Array Is Sorted", difficulty: "Medium", topic: "Two Pointers" },
  { question_name: "3Sum", difficulty: "Medium", topic: "Two Pointers" },
  { question_name: "Container With Most Water", difficulty: "Medium", topic: "Two Pointers" },
  { question_name: "Sort Colors", difficulty: "Medium", topic: "Two Pointers" },
  { question_name: "Trapping Rain Water", difficulty: "Hard", topic: "Two Pointers" },
  { question_name: "Move Zeroes", difficulty: "Easy", topic: "Two Pointers" },
  { question_name: "Remove Duplicates from Sorted Array II", difficulty: "Medium", topic: "Two Pointers" },
  { question_name: "Valid Anagram", difficulty: "Easy", topic: "Hashing" },
  { question_name: "Group Anagrams", difficulty: "Medium", topic: "Hashing" },
  { question_name: "Longest Common Prefix", difficulty: "Easy", topic: "String" },
  { question_name: "String to Integer (atoi)", difficulty: "Medium", topic: "String" },
  { question_name: "Longest Palindromic Substring", difficulty: "Medium", topic: "String" },
  { question_name: "Palindromic Substrings", difficulty: "Medium", topic: "String" },
  { question_name: "Reverse Words in a String", difficulty: "Medium", topic: "String" },
  { question_name: "Valid Parentheses", difficulty: "Easy", topic: "Stack" },
  { question_name: "4Sum", difficulty: "Medium", topic: "Two Pointers" },
  { question_name: "Subarray Sum Equals K", difficulty: "Medium", topic: "Prefix Sum" },
  { question_name: "Majority Element", difficulty: "Easy", topic: "Array" },
  { question_name: "Next Permutation", difficulty: "Medium", topic: "Array" },
 
  // Week 2 - Sliding Window, Hashing, Prefix Sums
  { question_name: "Maximum Average Subarray I", difficulty: "Easy", topic: "Sliding Window" },
  { question_name: "Longest Substring Without Repeating Characters", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Permutation in String", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Find All Anagrams in a String", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Minimum Size Subarray Sum", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Minimum Window Substring", difficulty: "Hard", topic: "Sliding Window" },
  { question_name: "Longest Repeating Character Replacement", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Fruit Into Baskets", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Ransom Note", difficulty: "Easy", topic: "Hashing" },
  { question_name: "Top K Frequent Elements", difficulty: "Medium", topic: "Heap" },
  { question_name: "Longest Consecutive Sequence", difficulty: "Medium", topic: "Hashing" },
  { question_name: "Isomorphic Strings", difficulty: "Easy", topic: "Hashing" },
  { question_name: "Copy List with Random Pointer", difficulty: "Medium", topic: "Linked List" },
  { question_name: "4Sum II", difficulty: "Medium", topic: "Hashing" },
  { question_name: "Encode and Decode Strings", difficulty: "Medium", topic: "String" },
  { question_name: "Range Sum Query - Immutable", difficulty: "Easy", topic: "Prefix Sum" },
  { question_name: "Merge Intervals", difficulty: "Medium", topic: "Intervals" },
  { question_name: "Insert Interval", difficulty: "Medium", topic: "Intervals" },
  { question_name: "Non-overlapping Intervals", difficulty: "Medium", topic: "Intervals" },
  { question_name: "Meeting Rooms II", difficulty: "Medium", topic: "Intervals" },
  { question_name: "Continuous Subarray Sum", difficulty: "Medium", topic: "Prefix Sum" },
  { question_name: "Subarray Product Less Than K", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "Minimum Number of Arrows to Burst Balloons", difficulty: "Medium", topic: "Intervals" },
  { question_name: "Longest Substring with At Most K Distinct Characters", difficulty: "Medium", topic: "Sliding Window" },
  { question_name: "3Sum Closest", difficulty: "Medium", topic: "Two Pointers" },
 
  // Week 3 - Stacks, Queues, Linked Lists
  { question_name: "Min Stack", difficulty: "Medium", topic: "Stack" },
  { question_name: "Evaluate Reverse Polish Notation", difficulty: "Medium", topic: "Stack" },
  { question_name: "Daily Temperatures", difficulty: "Medium", topic: "Stack" },
  { question_name: "Next Greater Element I", difficulty: "Easy", topic: "Stack" },
  { question_name: "Largest Rectangle in Histogram", difficulty: "Hard", topic: "Stack" },
  { question_name: "Online Stock Span", difficulty: "Medium", topic: "Stack" },
  { question_name: "Sliding Window Maximum", difficulty: "Hard", topic: "Queue" },
  { question_name: "Implement Queue using Stacks", difficulty: "Easy", topic: "Queue" },
  { question_name: "Design Circular Queue", difficulty: "Medium", topic: "Queue" },
  { question_name: "Task Scheduler", difficulty: "Medium", topic: "Greedy" },
  { question_name: "Reverse Linked List", difficulty: "Easy", topic: "Linked List" },
  { question_name: "Merge Two Sorted Lists", difficulty: "Easy", topic: "Linked List" },
  { question_name: "Linked List Cycle", difficulty: "Easy", topic: "Linked List" },
  { question_name: "Remove Nth Node From End of List", difficulty: "Medium", topic: "Linked List" },
  { question_name: "Reorder List", difficulty: "Medium", topic: "Linked List" },
  { question_name: "Add Two Numbers", difficulty: "Medium", topic: "Linked List" },
  { question_name: "Odd Even Linked List", difficulty: "Medium", topic: "Linked List" },
  { question_name: "Merge k Sorted Lists", difficulty: "Hard", topic: "Heap" },
  { question_name: "Reverse Nodes in k-Group", difficulty: "Hard", topic: "Linked List" },
  { question_name: "Rotate List", difficulty: "Medium", topic: "Linked List" },
  { question_name: "Palindrome Linked List", difficulty: "Easy", topic: "Linked List" },
  { question_name: "LRU Cache", difficulty: "Medium", topic: "Design" },
  { question_name: "LFU Cache", difficulty: "Hard", topic: "Design" },
 
  // Week 4 - Binary Search, Recursion, Sorting, Matrix
  { question_name: "Binary Search", difficulty: "Easy", topic: "Binary Search" },
  { question_name: "Search in Rotated Sorted Array", difficulty: "Medium", topic: "Binary Search" },
  { question_name: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", topic: "Binary Search" },
  { question_name: "Search a 2D Matrix", difficulty: "Medium", topic: "Binary Search" },
  { question_name: "Find First and Last Position of Element in Sorted Array", difficulty: "Medium", topic: "Binary Search" },
  { question_name: "Median of Two Sorted Arrays", difficulty: "Hard", topic: "Binary Search" },
  { question_name: "Koko Eating Bananas", difficulty: "Medium", topic: "Binary Search" },
  { question_name: "Split Array Largest Sum", difficulty: "Hard", topic: "Binary Search" },
  { question_name: "Pow(x, n)", difficulty: "Medium", topic: "Recursion" },
  { question_name: "Sqrt(x)", difficulty: "Easy", topic: "Binary Search" },
  { question_name: "Kth Largest Element in an Array", difficulty: "Medium", topic: "Heap" },
  { question_name: "Sort an Array", difficulty: "Medium", topic: "Sorting" },
  { question_name: "Meeting Rooms", difficulty: "Easy", topic: "Intervals" },
  { question_name: "Kth Smallest Element in a Sorted Matrix", difficulty: "Medium", topic: "Heap" },
  { question_name: "Wiggle Sort II", difficulty: "Medium", topic: "Sorting" },
  { question_name: "Rotate Image", difficulty: "Medium", topic: "Matrix" },
  { question_name: "Spiral Matrix", difficulty: "Medium", topic: "Matrix" },
  { question_name: "Word Search", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "Number of Islands", difficulty: "Medium", topic: "Graph" },
  { question_name: "Diagonal Traverse", difficulty: "Easy", topic: "Matrix" },
  { question_name: "Game of Life", difficulty: "Medium", topic: "Matrix" },
  { question_name: "Search a 2D Matrix II", difficulty: "Medium", topic: "Matrix" },
  { question_name: "Find Peak Element", difficulty: "Medium", topic: "Binary Search" },
  { question_name: "Search Insert Position", difficulty: "Easy", topic: "Binary Search" },
 
  // Week 5 - Trees & BST
  { question_name: "Binary Tree Inorder Traversal", difficulty: "Easy", topic: "Tree" },
  { question_name: "Maximum Depth of Binary Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Same Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Binary Tree Level Order Traversal", difficulty: "Medium", topic: "Tree" },
  { question_name: "Invert Binary Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Symmetric Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Diameter of Binary Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Balanced Binary Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Validate Binary Search Tree", difficulty: "Medium", topic: "Tree" },
  { question_name: "Insert into a Binary Search Tree", difficulty: "Medium", topic: "Tree" },
  { question_name: "Kth Smallest Element in a BST", difficulty: "Medium", topic: "Tree" },
  { question_name: "Lowest Common Ancestor of a Binary Search Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", topic: "Tree" },
  { question_name: "Convert Sorted Array to Binary Search Tree", difficulty: "Easy", topic: "Tree" },
  { question_name: "Populating Next Right Pointers in Each Node", difficulty: "Medium", topic: "Tree" },
  { question_name: "Flatten Binary Tree to Linked List", difficulty: "Medium", topic: "Tree" },
  { question_name: "Path Sum II", difficulty: "Medium", topic: "Tree" },
  { question_name: "Binary Tree Maximum Path Sum", difficulty: "Hard", topic: "Tree" },
  { question_name: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", topic: "Tree" },
  { question_name: "Sum Root to Leaf Numbers", difficulty: "Medium", topic: "Tree" },
  { question_name: "Serialize and Deserialize Binary Tree", difficulty: "Hard", topic: "Tree" },
  { question_name: "Binary Tree Right Side View", difficulty: "Medium", topic: "Tree" },
  { question_name: "Count Good Nodes in Binary Tree", difficulty: "Medium", topic: "Tree" },
  { question_name: "All Nodes Distance K in Binary Tree", difficulty: "Medium", topic: "Tree" },
  { question_name: "Delete Node in a BST", difficulty: "Medium", topic: "Tree" },
  { question_name: "Merge Two Binary Trees", difficulty: "Easy", topic: "Tree" },
 
  // Week 6 - Graphs
  { question_name: "Clone Graph", difficulty: "Medium", topic: "Graph" },
  { question_name: "Max Area of Island", difficulty: "Medium", topic: "Graph" },
  { question_name: "Flood Fill", difficulty: "Easy", topic: "Graph" },
  { question_name: "Rotting Oranges", difficulty: "Medium", topic: "Graph" },
  { question_name: "01 Matrix", difficulty: "Medium", topic: "Graph" },
  { question_name: "Walls and Gates", difficulty: "Medium", topic: "Graph" },
  { question_name: "Surrounded Regions", difficulty: "Medium", topic: "Graph" },
  { question_name: "Course Schedule", difficulty: "Medium", topic: "Graph" },
  { question_name: "Course Schedule II", difficulty: "Medium", topic: "Graph" },
  { question_name: "Alien Dictionary", difficulty: "Hard", topic: "Graph" },
  { question_name: "Minimum Height Trees", difficulty: "Medium", topic: "Graph" },
  { question_name: "Number of Connected Components in an Undirected Graph", difficulty: "Medium", topic: "Graph" },
  { question_name: "Redundant Connection", difficulty: "Medium", topic: "Graph" },
  { question_name: "Graph Valid Tree", difficulty: "Medium", topic: "Graph" },
  { question_name: "Accounts Merge", difficulty: "Hard", topic: "Graph" },
  { question_name: "Network Delay Time", difficulty: "Medium", topic: "Graph" },
  { question_name: "Cheapest Flights Within K Stops", difficulty: "Medium", topic: "Graph" },
  { question_name: "Path With Minimum Effort", difficulty: "Medium", topic: "Graph" },
  { question_name: "Swim in Rising Water", difficulty: "Hard", topic: "Graph" },
  { question_name: "Pacific Atlantic Water Flow", difficulty: "Medium", topic: "Graph" },
  { question_name: "Word Ladder", difficulty: "Hard", topic: "Graph" },
  { question_name: "Is Graph Bipartite?", difficulty: "Medium", topic: "Graph" },
  { question_name: "Evaluate Division", difficulty: "Medium", topic: "Graph" },
  { question_name: "Number of Provinces", difficulty: "Easy", topic: "Graph" },
 
  // Week 7 - Dynamic Programming
  { question_name: "Climbing Stairs", difficulty: "Easy", topic: "DP" },
  { question_name: "House Robber", difficulty: "Medium", topic: "DP" },
  { question_name: "House Robber II", difficulty: "Medium", topic: "DP" },
  { question_name: "Decode Ways", difficulty: "Medium", topic: "DP" },
  { question_name: "Coin Change", difficulty: "Medium", topic: "DP" },
  { question_name: "Maximum Product Subarray", difficulty: "Medium", topic: "DP" },
  { question_name: "Longest Increasing Subsequence", difficulty: "Medium", topic: "DP" },
  { question_name: "Word Break", difficulty: "Medium", topic: "DP" },
  { question_name: "Unique Paths", difficulty: "Medium", topic: "DP" },
  { question_name: "Minimum Path Sum", difficulty: "Medium", topic: "DP" },
  { question_name: "Unique Paths II", difficulty: "Medium", topic: "DP" },
  { question_name: "Dungeon Game", difficulty: "Hard", topic: "DP" },
  { question_name: "Longest Common Subsequence", difficulty: "Medium", topic: "DP" },
  { question_name: "Edit Distance", difficulty: "Hard", topic: "DP" },
  { question_name: "Longest Palindromic Subsequence", difficulty: "Medium", topic: "DP" },
  { question_name: "Distinct Subsequences", difficulty: "Hard", topic: "DP" },
  { question_name: "Partition Equal Subset Sum", difficulty: "Medium", topic: "DP" },
  { question_name: "Target Sum", difficulty: "Medium", topic: "DP" },
  { question_name: "Combination Sum IV", difficulty: "Medium", topic: "DP" },
  { question_name: "Coin Change II", difficulty: "Medium", topic: "DP" },
  { question_name: "Best Time to Buy and Sell Stock III", difficulty: "Hard", topic: "DP" },
  { question_name: "Best Time to Buy and Sell Stock with Cooldown", difficulty: "Medium", topic: "DP" },
  { question_name: "Maximal Square", difficulty: "Medium", topic: "DP" },
  { question_name: "Interleaving String", difficulty: "Hard", topic: "DP" },
  { question_name: "Perfect Squares", difficulty: "Medium", topic: "DP" },
 
  // Week 8 - Backtracking, Greedy, Heaps, Tries, Design
  { question_name: "Subsets", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "Subsets II", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "Permutations", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "Combination Sum", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "Combination Sum II", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "N-Queens", difficulty: "Hard", topic: "Backtracking" },
  { question_name: "Palindrome Partitioning", difficulty: "Medium", topic: "Backtracking" },
  { question_name: "Jump Game", difficulty: "Medium", topic: "Greedy" },
  { question_name: "Jump Game II", difficulty: "Medium", topic: "Greedy" },
  { question_name: "Gas Station", difficulty: "Medium", topic: "Greedy" },
  { question_name: "Best Time to Buy and Sell Stock II", difficulty: "Easy", topic: "Greedy" },
  { question_name: "Kth Largest Element in a Stream", difficulty: "Easy", topic: "Heap" },
  { question_name: "Find Median from Data Stream", difficulty: "Hard", topic: "Heap" },
  { question_name: "Top K Frequent Words", difficulty: "Medium", topic: "Heap" },
  { question_name: "Implement Trie (Prefix Tree)", difficulty: "Medium", topic: "Trie" },
  { question_name: "Design Add and Search Words Data Structure", difficulty: "Medium", topic: "Trie" },
  { question_name: "Single Number", difficulty: "Easy", topic: "Bit Manipulation" },
  { question_name: "Number of 1 Bits", difficulty: "Easy", topic: "Bit Manipulation" },
  { question_name: "Design Twitter", difficulty: "Medium", topic: "Design" },
  { question_name: "Insert Delete GetRandom O(1)", difficulty: "Medium", topic: "Design" },
  { question_name: "Word Search II", difficulty: "Hard", topic: "Trie" },
];


export const seed = async()=>{

    try{

        await questionModel.deleteMany({})
        console.log("Inserting.......")
        const formatted_questions = questions.map((q)=>{
           return {question_name:q.question_name,difficulty:q.difficulty,topic:q.topic,isDone:false}
        })

        const inserted = await questionModel.insertMany(formatted_questions)
        console.log("Questions seeded")




    }catch(error){
        console.log(error.message)

    }

}

