import questionModel from "./models/question_schema.js";
const LC_BASE = "https://leetcode.com/problems";
const questions = [
  // Week 1 - Arrays, Strings, Two Pointers
  { question_name: "Two Sum", difficulty: "Easy", topic: "Hashing", slug: "two-sum" },
  { question_name: "Best Time to Buy and Sell Stock", difficulty: "Easy", topic: "Array", slug: "best-time-to-buy-and-sell-stock" },
  { question_name: "Contains Duplicate", difficulty: "Easy", topic: "Hashing", slug: "contains-duplicate" },
  { question_name: "Product of Array Except Self", difficulty: "Medium", topic: "Array", slug: "product-of-array-except-self" },
  { question_name: "Maximum Subarray", difficulty: "Medium", topic: "Array", slug: "maximum-subarray" },
  { question_name: "Rotate Array", difficulty: "Medium", topic: "Array", slug: "rotate-array" },
  { question_name: "Merge Sorted Array", difficulty: "Easy", topic: "Two Pointers", slug: "merge-sorted-array" },
  { question_name: "Set Matrix Zeroes", difficulty: "Medium", topic: "Matrix", slug: "set-matrix-zeroes" },
  { question_name: "Valid Palindrome", difficulty: "Easy", topic: "Two Pointers", slug: "valid-palindrome" },
  { question_name: "Two Sum II - Input Array Is Sorted", difficulty: "Medium", topic: "Two Pointers", slug: "two-sum-ii-input-array-is-sorted" },
  { question_name: "3Sum", difficulty: "Medium", topic: "Two Pointers", slug: "3sum" },
  { question_name: "Container With Most Water", difficulty: "Medium", topic: "Two Pointers", slug: "container-with-most-water" },
  { question_name: "Sort Colors", difficulty: "Medium", topic: "Two Pointers", slug: "sort-colors" },
  { question_name: "Trapping Rain Water", difficulty: "Hard", topic: "Two Pointers", slug: "trapping-rain-water" },
  { question_name: "Move Zeroes", difficulty: "Easy", topic: "Two Pointers", slug: "move-zeroes" },
  { question_name: "Remove Duplicates from Sorted Array II", difficulty: "Medium", topic: "Two Pointers", slug: "remove-duplicates-from-sorted-array-ii" },
  { question_name: "Valid Anagram", difficulty: "Easy", topic: "Hashing", slug: "valid-anagram" },
  { question_name: "Group Anagrams", difficulty: "Medium", topic: "Hashing", slug: "group-anagrams" },
  { question_name: "Longest Common Prefix", difficulty: "Easy", topic: "String", slug: "longest-common-prefix" },
  { question_name: "String to Integer (atoi)", difficulty: "Medium", topic: "String", slug: "string-to-integer-atoi" },
  { question_name: "Longest Palindromic Substring", difficulty: "Medium", topic: "String", slug: "longest-palindromic-substring" },
  { question_name: "Palindromic Substrings", difficulty: "Medium", topic: "String", slug: "palindromic-substrings" },
  { question_name: "Reverse Words in a String", difficulty: "Medium", topic: "String", slug: "reverse-words-in-a-string" },
  { question_name: "Valid Parentheses", difficulty: "Easy", topic: "Stack", slug: "valid-parentheses" },
  { question_name: "4Sum", difficulty: "Medium", topic: "Two Pointers", slug: "4sum" },
  { question_name: "Subarray Sum Equals K", difficulty: "Medium", topic: "Prefix Sum", slug: "subarray-sum-equals-k" },
  { question_name: "Majority Element", difficulty: "Easy", topic: "Array", slug: "majority-element" },
  { question_name: "Next Permutation", difficulty: "Medium", topic: "Array", slug: "next-permutation" },
 
  // Week 2 - Sliding Window, Hashing, Prefix Sums
  { question_name: "Maximum Average Subarray I", difficulty: "Easy", topic: "Sliding Window", slug: "maximum-average-subarray-i" },
  { question_name: "Longest Substring Without Repeating Characters", difficulty: "Medium", topic: "Sliding Window", slug: "longest-substring-without-repeating-characters" },
  { question_name: "Permutation in String", difficulty: "Medium", topic: "Sliding Window", slug: "permutation-in-string" },
  { question_name: "Find All Anagrams in a String", difficulty: "Medium", topic: "Sliding Window", slug: "find-all-anagrams-in-a-string" },
  { question_name: "Minimum Size Subarray Sum", difficulty: "Medium", topic: "Sliding Window", slug: "minimum-size-subarray-sum" },
  { question_name: "Minimum Window Substring", difficulty: "Hard", topic: "Sliding Window", slug: "minimum-window-substring" },
  { question_name: "Longest Repeating Character Replacement", difficulty: "Medium", topic: "Sliding Window", slug: "longest-repeating-character-replacement" },
  { question_name: "Fruit Into Baskets", difficulty: "Medium", topic: "Sliding Window", slug: "fruit-into-baskets" },
  { question_name: "Ransom Note", difficulty: "Easy", topic: "Hashing", slug: "ransom-note" },
  { question_name: "Top K Frequent Elements", difficulty: "Medium", topic: "Heap", slug: "top-k-frequent-elements" },
  { question_name: "Longest Consecutive Sequence", difficulty: "Medium", topic: "Hashing", slug: "longest-consecutive-sequence" },
  { question_name: "Isomorphic Strings", difficulty: "Easy", topic: "Hashing", slug: "isomorphic-strings" },
  { question_name: "Copy List with Random Pointer", difficulty: "Medium", topic: "Linked List", slug: "copy-list-with-random-pointer" },
  { question_name: "4Sum II", difficulty: "Medium", topic: "Hashing", slug: "4sum-ii" },
  { question_name: "Encode and Decode Strings", difficulty: "Medium", topic: "String", slug: "encode-and-decode-strings" },
  { question_name: "Range Sum Query - Immutable", difficulty: "Easy", topic: "Prefix Sum", slug: "range-sum-query-immutable" },
  { question_name: "Merge Intervals", difficulty: "Medium", topic: "Intervals", slug: "merge-intervals" },
  { question_name: "Insert Interval", difficulty: "Medium", topic: "Intervals", slug: "insert-interval" },
  { question_name: "Non-overlapping Intervals", difficulty: "Medium", topic: "Intervals", slug: "non-overlapping-intervals" },
  { question_name: "Meeting Rooms II", difficulty: "Medium", topic: "Intervals", slug: "meeting-rooms-ii" },
  { question_name: "Continuous Subarray Sum", difficulty: "Medium", topic: "Prefix Sum", slug: "continuous-subarray-sum" },
  { question_name: "Subarray Product Less Than K", difficulty: "Medium", topic: "Sliding Window", slug: "subarray-product-less-than-k" },
  { question_name: "Minimum Number of Arrows to Burst Balloons", difficulty: "Medium", topic: "Intervals", slug: "minimum-number-of-arrows-to-burst-balloons" },
  { question_name: "Longest Substring with At Most K Distinct Characters", difficulty: "Medium", topic: "Sliding Window", slug: "longest-substring-with-at-most-k-distinct-characters" },
  { question_name: "3Sum Closest", difficulty: "Medium", topic: "Two Pointers", slug: "3sum-closest" },
 
  // Week 3 - Stacks, Queues, Linked Lists
  { question_name: "Min Stack", difficulty: "Medium", topic: "Stack", slug: "min-stack" },
  { question_name: "Evaluate Reverse Polish Notation", difficulty: "Medium", topic: "Stack", slug: "evaluate-reverse-polish-notation" },
  { question_name: "Daily Temperatures", difficulty: "Medium", topic: "Stack", slug: "daily-temperatures" },
  { question_name: "Next Greater Element I", difficulty: "Easy", topic: "Stack", slug: "next-greater-element-i" },
  { question_name: "Largest Rectangle in Histogram", difficulty: "Hard", topic: "Stack", slug: "largest-rectangle-in-histogram" },
  { question_name: "Online Stock Span", difficulty: "Medium", topic: "Stack", slug: "online-stock-span" },
  { question_name: "Sliding Window Maximum", difficulty: "Hard", topic: "Queue", slug: "sliding-window-maximum" },
  { question_name: "Implement Queue using Stacks", difficulty: "Easy", topic: "Queue", slug: "implement-queue-using-stacks" },
  { question_name: "Design Circular Queue", difficulty: "Medium", topic: "Queue", slug: "design-circular-queue" },
  { question_name: "Task Scheduler", difficulty: "Medium", topic: "Greedy", slug: "task-scheduler" },
  { question_name: "Reverse Linked List", difficulty: "Easy", topic: "Linked List", slug: "reverse-linked-list" },
  { question_name: "Merge Two Sorted Lists", difficulty: "Easy", topic: "Linked List", slug: "merge-two-sorted-lists" },
  { question_name: "Linked List Cycle", difficulty: "Easy", topic: "Linked List", slug: "linked-list-cycle" },
  { question_name: "Remove Nth Node From End of List", difficulty: "Medium", topic: "Linked List", slug: "remove-nth-node-from-end-of-list" },
  { question_name: "Reorder List", difficulty: "Medium", topic: "Linked List", slug: "reorder-list" },
  { question_name: "Add Two Numbers", difficulty: "Medium", topic: "Linked List", slug: "add-two-numbers" },
  { question_name: "Odd Even Linked List", difficulty: "Medium", topic: "Linked List", slug: "odd-even-linked-list" },
  { question_name: "Merge k Sorted Lists", difficulty: "Hard", topic: "Heap", slug: "merge-k-sorted-lists" },
  { question_name: "Reverse Nodes in k-Group", difficulty: "Hard", topic: "Linked List", slug: "reverse-nodes-in-k-group" },
  { question_name: "Rotate List", difficulty: "Medium", topic: "Linked List", slug: "rotate-list" },
  { question_name: "Palindrome Linked List", difficulty: "Easy", topic: "Linked List", slug: "palindrome-linked-list" },
  { question_name: "LRU Cache", difficulty: "Medium", topic: "Design", slug: "lru-cache" },
  { question_name: "LFU Cache", difficulty: "Hard", topic: "Design", slug: "lfu-cache" },
 
  // Week 4 - Binary Search, Recursion, Sorting, Matrix
  { question_name: "Binary Search", difficulty: "Easy", topic: "Binary Search", slug: "binary-search" },
  { question_name: "Search in Rotated Sorted Array", difficulty: "Medium", topic: "Binary Search", slug: "search-in-rotated-sorted-array" },
  { question_name: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", topic: "Binary Search", slug: "find-minimum-in-rotated-sorted-array" },
  { question_name: "Search a 2D Matrix", difficulty: "Medium", topic: "Binary Search", slug: "search-a-2d-matrix" },
  { question_name: "Find First and Last Position of Element in Sorted Array", difficulty: "Medium", topic: "Binary Search", slug: "find-first-and-last-position-of-element-in-sorted-array" },
  { question_name: "Median of Two Sorted Arrays", difficulty: "Hard", topic: "Binary Search", slug: "median-of-two-sorted-arrays" },
  { question_name: "Koko Eating Bananas", difficulty: "Medium", topic: "Binary Search", slug: "koko-eating-bananas" },
  { question_name: "Split Array Largest Sum", difficulty: "Hard", topic: "Binary Search", slug: "split-array-largest-sum" },
  { question_name: "Pow(x, n)", difficulty: "Medium", topic: "Recursion", slug: "powx-n" },
  { question_name: "Sqrt(x)", difficulty: "Easy", topic: "Binary Search", slug: "sqrtx" },
  { question_name: "Kth Largest Element in an Array", difficulty: "Medium", topic: "Heap", slug: "kth-largest-element-in-an-array" },
  { question_name: "Sort an Array", difficulty: "Medium", topic: "Sorting", slug: "sort-an-array" },
  { question_name: "Meeting Rooms", difficulty: "Easy", topic: "Intervals", slug: "meeting-rooms" },
  { question_name: "Kth Smallest Element in a Sorted Matrix", difficulty: "Medium", topic: "Heap", slug: "kth-smallest-element-in-a-sorted-matrix" },
  { question_name: "Wiggle Sort II", difficulty: "Medium", topic: "Sorting", slug: "wiggle-sort-ii" },
  { question_name: "Rotate Image", difficulty: "Medium", topic: "Matrix", slug: "rotate-image" },
  { question_name: "Spiral Matrix", difficulty: "Medium", topic: "Matrix", slug: "spiral-matrix" },
  { question_name: "Word Search", difficulty: "Medium", topic: "Backtracking", slug: "word-search" },
  { question_name: "Number of Islands", difficulty: "Medium", topic: "Graph", slug: "number-of-islands" },
  { question_name: "Diagonal Traverse", difficulty: "Easy", topic: "Matrix", slug: "diagonal-traverse" },
  { question_name: "Game of Life", difficulty: "Medium", topic: "Matrix", slug: "game-of-life" },
  { question_name: "Search a 2D Matrix II", difficulty: "Medium", topic: "Matrix", slug: "search-a-2d-matrix-ii" },
  { question_name: "Find Peak Element", difficulty: "Medium", topic: "Binary Search", slug: "find-peak-element" },
  { question_name: "Search Insert Position", difficulty: "Easy", topic: "Binary Search", slug: "search-insert-position" },
 
  // Week 5 - Trees & BST
  { question_name: "Binary Tree Inorder Traversal", difficulty: "Easy", topic: "Tree", slug: "binary-tree-inorder-traversal" },
  { question_name: "Maximum Depth of Binary Tree", difficulty: "Easy", topic: "Tree", slug: "maximum-depth-of-binary-tree" },
  { question_name: "Same Tree", difficulty: "Easy", topic: "Tree", slug: "same-tree" },
  { question_name: "Binary Tree Level Order Traversal", difficulty: "Medium", topic: "Tree", slug: "binary-tree-level-order-traversal" },
  { question_name: "Invert Binary Tree", difficulty: "Easy", topic: "Tree", slug: "invert-binary-tree" },
  { question_name: "Symmetric Tree", difficulty: "Easy", topic: "Tree", slug: "symmetric-tree" },
  { question_name: "Diameter of Binary Tree", difficulty: "Easy", topic: "Tree", slug: "diameter-of-binary-tree" },
  { question_name: "Balanced Binary Tree", difficulty: "Easy", topic: "Tree", slug: "balanced-binary-tree" },
  { question_name: "Validate Binary Search Tree", difficulty: "Medium", topic: "Tree", slug: "validate-binary-search-tree" },
  { question_name: "Insert into a Binary Search Tree", difficulty: "Medium", topic: "Tree", slug: "insert-into-a-binary-search-tree" },
  { question_name: "Kth Smallest Element in a BST", difficulty: "Medium", topic: "Tree", slug: "kth-smallest-element-in-a-bst" },
  { question_name: "Lowest Common Ancestor of a Binary Search Tree", difficulty: "Easy", topic: "Tree", slug: "lowest-common-ancestor-of-a-binary-search-tree" },
  { question_name: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", topic: "Tree", slug: "construct-binary-tree-from-preorder-and-inorder-traversal" },
  { question_name: "Convert Sorted Array to Binary Search Tree", difficulty: "Easy", topic: "Tree", slug: "convert-sorted-array-to-binary-search-tree" },
  { question_name: "Populating Next Right Pointers in Each Node", difficulty: "Medium", topic: "Tree", slug: "populating-next-right-pointers-in-each-node" },
  { question_name: "Flatten Binary Tree to Linked List", difficulty: "Medium", topic: "Tree", slug: "flatten-binary-tree-to-linked-list" },
  { question_name: "Path Sum II", difficulty: "Medium", topic: "Tree", slug: "path-sum-ii" },
  { question_name: "Binary Tree Maximum Path Sum", difficulty: "Hard", topic: "Tree", slug: "binary-tree-maximum-path-sum" },
  { question_name: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", topic: "Tree", slug: "lowest-common-ancestor-of-a-binary-tree" },
  { question_name: "Sum Root to Leaf Numbers", difficulty: "Medium", topic: "Tree", slug: "sum-root-to-leaf-numbers" },
  { question_name: "Serialize and Deserialize Binary Tree", difficulty: "Hard", topic: "Tree", slug: "serialize-and-deserialize-binary-tree" },
  { question_name: "Binary Tree Right Side View", difficulty: "Medium", topic: "Tree", slug: "binary-tree-right-side-view" },
  { question_name: "Count Good Nodes in Binary Tree", difficulty: "Medium", topic: "Tree", slug: "count-good-nodes-in-binary-tree" },
  { question_name: "All Nodes Distance K in Binary Tree", difficulty: "Medium", topic: "Tree", slug: "all-nodes-distance-k-in-binary-tree" },
  { question_name: "Delete Node in a BST", difficulty: "Medium", topic: "Tree", slug: "delete-node-in-a-bst" },
  { question_name: "Merge Two Binary Trees", difficulty: "Easy", topic: "Tree", slug: "merge-two-binary-trees" },
 
  // Week 6 - Graphs
  { question_name: "Clone Graph", difficulty: "Medium", topic: "Graph", slug: "clone-graph" },
  { question_name: "Max Area of Island", difficulty: "Medium", topic: "Graph", slug: "max-area-of-island" },
  { question_name: "Flood Fill", difficulty: "Easy", topic: "Graph", slug: "flood-fill" },
  { question_name: "Rotting Oranges", difficulty: "Medium", topic: "Graph", slug: "rotting-oranges" },
  { question_name: "01 Matrix", difficulty: "Medium", topic: "Graph", slug: "01-matrix" },
  { question_name: "Walls and Gates", difficulty: "Medium", topic: "Graph", slug: "walls-and-gates" },
  { question_name: "Surrounded Regions", difficulty: "Medium", topic: "Graph", slug: "surrounded-regions" },
  { question_name: "Course Schedule", difficulty: "Medium", topic: "Graph", slug: "course-schedule" },
  { question_name: "Course Schedule II", difficulty: "Medium", topic: "Graph", slug: "course-schedule-ii" },
  { question_name: "Alien Dictionary", difficulty: "Hard", topic: "Graph", slug: "alien-dictionary" },
  { question_name: "Minimum Height Trees", difficulty: "Medium", topic: "Graph", slug: "minimum-height-trees" },
  { question_name: "Number of Connected Components in an Undirected Graph", difficulty: "Medium", topic: "Graph", slug: "number-of-connected-components-in-an-undirected-graph" },
  { question_name: "Redundant Connection", difficulty: "Medium", topic: "Graph", slug: "redundant-connection" },
  { question_name: "Graph Valid Tree", difficulty: "Medium", topic: "Graph", slug: "graph-valid-tree" },
  { question_name: "Accounts Merge", difficulty: "Hard", topic: "Graph", slug: "accounts-merge" },
  { question_name: "Network Delay Time", difficulty: "Medium", topic: "Graph", slug: "network-delay-time" },
  { question_name: "Cheapest Flights Within K Stops", difficulty: "Medium", topic: "Graph", slug: "cheapest-flights-within-k-stops" },
  { question_name: "Path With Minimum Effort", difficulty: "Medium", topic: "Graph", slug: "path-with-minimum-effort" },
  { question_name: "Swim in Rising Water", difficulty: "Hard", topic: "Graph", slug: "swim-in-rising-water" },
  { question_name: "Pacific Atlantic Water Flow", difficulty: "Medium", topic: "Graph", slug: "pacific-atlantic-water-flow" },
  { question_name: "Word Ladder", difficulty: "Hard", topic: "Graph", slug: "word-ladder" },
  { question_name: "Is Graph Bipartite?", difficulty: "Medium", topic: "Graph", slug: "is-graph-bipartite" },
  { question_name: "Evaluate Division", difficulty: "Medium", topic: "Graph", slug: "evaluate-division" },
  { question_name: "Number of Provinces", difficulty: "Easy", topic: "Graph", slug: "number-of-provinces" },
 
  // Week 7 - Dynamic Programming
  { question_name: "Climbing Stairs", difficulty: "Easy", topic: "DP", slug: "climbing-stairs" },
  { question_name: "House Robber", difficulty: "Medium", topic: "DP", slug: "house-robber" },
  { question_name: "House Robber II", difficulty: "Medium", topic: "DP", slug: "house-robber-ii" },
  { question_name: "Decode Ways", difficulty: "Medium", topic: "DP", slug: "decode-ways" },
  { question_name: "Coin Change", difficulty: "Medium", topic: "DP", slug: "coin-change" },
  { question_name: "Maximum Product Subarray", difficulty: "Medium", topic: "DP", slug: "maximum-product-subarray" },
  { question_name: "Longest Increasing Subsequence", difficulty: "Medium", topic: "DP", slug: "longest-increasing-subsequence" },
  { question_name: "Word Break", difficulty: "Medium", topic: "DP", slug: "word-break" },
  { question_name: "Unique Paths", difficulty: "Medium", topic: "DP", slug: "unique-paths" },
  { question_name: "Minimum Path Sum", difficulty: "Medium", topic: "DP", slug: "minimum-path-sum" },
  { question_name: "Unique Paths II", difficulty: "Medium", topic: "DP", slug: "unique-paths-ii" },
  { question_name: "Dungeon Game", difficulty: "Hard", topic: "DP", slug: "dungeon-game" },
  { question_name: "Longest Common Subsequence", difficulty: "Medium", topic: "DP", slug: "longest-common-subsequence" },
  { question_name: "Edit Distance", difficulty: "Hard", topic: "DP", slug: "edit-distance" },
  { question_name: "Longest Palindromic Subsequence", difficulty: "Medium", topic: "DP", slug: "longest-palindromic-subsequence" },
  { question_name: "Distinct Subsequences", difficulty: "Hard", topic: "DP", slug: "distinct-subsequences" },
  { question_name: "Partition Equal Subset Sum", difficulty: "Medium", topic: "DP", slug: "partition-equal-subset-sum" },
  { question_name: "Target Sum", difficulty: "Medium", topic: "DP", slug: "target-sum" },
  { question_name: "Combination Sum IV", difficulty: "Medium", topic: "DP", slug: "combination-sum-iv" },
  { question_name: "Coin Change II", difficulty: "Medium", topic: "DP", slug: "coin-change-ii" },
  { question_name: "Best Time to Buy and Sell Stock III", difficulty: "Hard", topic: "DP", slug: "best-time-to-buy-and-sell-stock-iii" },
  { question_name: "Best Time to Buy and Sell Stock with Cooldown", difficulty: "Medium", topic: "DP", slug: "best-time-to-buy-and-sell-stock-with-cooldown" },
  { question_name: "Maximal Square", difficulty: "Medium", topic: "DP", slug: "maximal-square" },
  { question_name: "Interleaving String", difficulty: "Hard", topic: "DP", slug: "interleaving-string" },
  { question_name: "Perfect Squares", difficulty: "Medium", topic: "DP", slug: "perfect-squares" },
 
  // Week 8 - Backtracking, Greedy, Heaps, Tries, Design
  { question_name: "Subsets", difficulty: "Medium", topic: "Backtracking", slug: "subsets" },
  { question_name: "Subsets II", difficulty: "Medium", topic: "Backtracking", slug: "subsets-ii" },
  { question_name: "Permutations", difficulty: "Medium", topic: "Backtracking", slug: "permutations" },
  { question_name: "Combination Sum", difficulty: "Medium", topic: "Backtracking", slug: "combination-sum" },
  { question_name: "Combination Sum II", difficulty: "Medium", topic: "Backtracking", slug: "combination-sum-ii" },
  { question_name: "N-Queens", difficulty: "Hard", topic: "Backtracking", slug: "n-queens" },
  { question_name: "Palindrome Partitioning", difficulty: "Medium", topic: "Backtracking", slug: "palindrome-partitioning" },
  { question_name: "Jump Game", difficulty: "Medium", topic: "Greedy", slug: "jump-game" },
  { question_name: "Jump Game II", difficulty: "Medium", topic: "Greedy", slug: "jump-game-ii" },
  { question_name: "Gas Station", difficulty: "Medium", topic: "Greedy", slug: "gas-station" },
  { question_name: "Best Time to Buy and Sell Stock II", difficulty: "Easy", topic: "Greedy", slug: "best-time-to-buy-and-sell-stock-ii" },
  { question_name: "Kth Largest Element in a Stream", difficulty: "Easy", topic: "Heap", slug: "kth-largest-element-in-a-stream" },
  { question_name: "Find Median from Data Stream", difficulty: "Hard", topic: "Heap", slug: "find-median-from-data-stream" },
  { question_name: "Top K Frequent Words", difficulty: "Medium", topic: "Heap", slug: "top-k-frequent-words" },
  { question_name: "Implement Trie (Prefix Tree)", difficulty: "Medium", topic: "Trie", slug: "implement-trie-prefix-tree" },
  { question_name: "Design Add and Search Words Data Structure", difficulty: "Medium", topic: "Trie", slug: "design-add-and-search-words-data-structure" },
  { question_name: "Single Number", difficulty: "Easy", topic: "Bit Manipulation", slug: "single-number" },
  { question_name: "Number of 1 Bits", difficulty: "Easy", topic: "Bit Manipulation", slug: "number-of-1-bits" },
  { question_name: "Design Twitter", difficulty: "Medium", topic: "Design", slug: "design-twitter" },
  { question_name: "Insert Delete GetRandom O(1)", difficulty: "Medium", topic: "Design", slug: "insert-delete-getrandom-o1" },
  { question_name: "Word Search II", difficulty: "Hard", topic: "Trie", slug: "word-search-ii" },
];



export const seed = async()=>{

    try{

        await questionModel.deleteMany({})
        console.log("Inserting.......")
        const formatted_questions = questions.map((q)=>{
           return {question_name:q.question_name,difficulty:q.difficulty,topic:q.topic,isDone:false,leetcode_link:`${LC_BASE}/${q.slug}`}
        })

        const inserted = await questionModel.insertMany(formatted_questions)
        console.log("Questions seeded")




    }catch(error){
        console.log(error.message)

    }

}

